### ISSUE TITLE
Please refrain from testing your Python script on public servers aka IDK HOW TO READ

### ISSUE THREAD

**Issue by x1y** [acidvegas/efknockr#1]
Dear @acidvegas, please refrain from testing your bungling Python script on public servers.

After the commit https://github.com/acidvegas/efknockr/commit/44c1743be7491a4fda8a51cb5128f6f8edeaac9d from September 17th it appears that you tested it on a public server September 21st. 

Before the commit https://github.com/acidvegas/efknockr/commit/108343167cdb7b89d71c8d33cc450292f0938409 from July 10th you tested it on July 4th on the same public server.

With the recent age of the script and its unrenownedness, it is quite obvious who it is who is using it.

![1695311217](https://github.com/acidvegas/efknockr/assets/23239177/de414d78-8e44-4e02-a053-d15c0915728f)

Regards

**Comment by acidvegas** [comment]
[You arent very smart lol....](https://github.com/acidvegas/weechat/blob/master/alias.conf#L105)


Closed cause this has nothing at all to do with efknockr
